name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: Run Rubocop
        run: cd collective_blog/ && make lint
      
      - name: Run Test
        run: cd collective_blog/ && make test
