name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          bundler-cache: true

      - name: Install dependencies
        run: cd collective_blog/ && make install

      - name: Run Rubocop
        run: cd collective_blog/ && make lint
      
      - name: Run Test
        run: cd collective_blog/ && make test