name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: Install dependencies
        run: ../collective_blog/make install

      - name: Run Rubocop
        run: ../collective_blog/make lint
      
      - name: Run Test
        run: ../collective_blog/make test
